const ActionTypes = {
    ADDTODO: 'ADDTODO',
    DELETETODO: 'DELETETODO',
    EDITTODO: 'EDITTODO',
    VIEWTODOS: 'VIEWTODOS',
    UPDATETODOS: "UPDATETODOS",
    GETKEYS: 'GETKEYS'
}

export default ActionTypes;